#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8

#### AutoStart Application ####
wal -R
xsetroot -cursor_name left_ptr &
xset dpms 0 0 0 &
xset -dpms & # you might don't want this it disables the screen saver
xset r rate 190 60 s noblank & 
xset s 0 0 &
dunst &
# $HOME/.config/scripts/killit.sh polybar & #change this to just 'picom &' if you didn't use the killit.sh. the script just kills the picom server every time you refresh bspwm

polybar -c ${HOME}/.config/polybar/config.ini &

# xcompmgr -r 2 -f 0.2,0.2 & # tryed this composor for animations cuz at that time picom was not working but now it works...

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#### window config ####
bspc config border_width         2
bspc config window_gap			 8
# bspc config border_radius        13

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

#window apperiance
bspc rule -a Gimp desktop='^4' follow=on
bspc rule -a Shotcut desktop='^4' follow=on focus=on
bspc rule -a obs desktop='^5' follow=on focus=on
bspc rule -a Code desktop='^1' follow=on focus=on
bspc rule -a kdenlive desktop='^4' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Steam desktop='^5' follow=on focus=on
bspc rule -a Spotify desktop='^4' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ffplay state=floating focus=on
bspc rule -a Pcmanfm state=tiled focus=on
bspc rule -a mpv state=floating focus=on
bspc rule -a whatsdesk desktop='^3' follow=on focus=on
bspc rule -a MonoDevelop dekstop='^4' follow=on focus=on
bspc rule -a qBittorrent desktop='^8' follow=on focus=on
bspc rule -a thorium-browser desktop='^2' follow=on focus=on

#### Border ####
# source the colors.
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
